function [result] = test_channel_coding_pdc(tx_config)
    % create transmitter
    tx = lib_types.tx_t(tx_config);

    % generate random bits
    tb_bits = randi([0 1], tx.phy_4_5.N_TB_bits, 1);

    % encode PDC
    [x_PDC, ~] = lib_7_transmission_encoding.PDC_encoding(tb_bits, ...
                                                          tx.phy_4_5.G, ...
                                                          tx_config.Z, ...
                                                          tx_config.network_id, ...
                                                          tx_config.PLCF_type, ...
                                                          tx_config.rv, ...
                                                          tx.phy_4_5.mcs, ...
                                                          tx.phy_4_5.tm_mode.N_SS);

    % simulate without HARQ
    HARQ_buf_ = [];

    % decode PDC
    [tb_bits_recovered, ~, ~] = lib_7_transmission_encoding.PDC_decoding(x_PDC, ...
                                                                         tx.phy_4_5.N_TB_bits, ...
                                                                         tx_config.Z, ...
                                                                         tx_config.network_id, ...
                                                                         tx_config.PLCF_type, ...
                                                                         tx_config.rv, ...
                                                                         tx.phy_4_5.mcs, ...
                                                                         tx.phy_4_5.tm_mode.N_SS, ...
                                                                         HARQ_buf_);

    % analyze result
    result.n_bit_errors = sum(abs(tb_bits - double(tb_bits_recovered)));
    result.BER = result.n_bit_errors / tx.phy_4_5.N_TB_bits;
end